from __future__ import annotations

import datetime as dt
import json
import math
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Sequence

from .db import count_games


DEFAULT_SITE_URL = "https://arammeta.com/"
# Cloudflare Web Analytics beacon token for arammeta.com.  PUBLIC by design -- it
# ships in the client HTML (visible in view-source), so it lives in source, not a
# secret.  build_tier_list injects the beacon <script> when given this token; the
# watchdog publisher is the only path that reaches the live site, so wiring it here
# covers production.  Like DEFAULT_SITE_URL this is imported in-process, so a change
# needs a publisher restart (or a one-shot `publish_static_site.py --once --force`).
DEFAULT_CF_ANALYTICS_TOKEN = "483cb89af9ee4d1da31ce69cee310b49"
DEFAULT_STATE_PATH = Path("data/site/static_publish_state.json")

# Empirical (champion x team-archetype) comp-fit radar.  Regenerated by
# scripts/build_champ_archetype_fit.py AFTER the tier list (it reads the rebuilt
# tier-list.json champ.comp vectors) and shipped alongside it.  It reads the
# pooled cross-patch parquet the +25% recommender refresh keeps current
# (mayhem_pooled_auto.parquet); if that is absent it falls back to the fixed
# 16.10-16.12 snapshot so a fresh checkout / clean env still builds.
COMP_FIT_PAYLOAD = Path("docs/api/tier-list.json")
COMP_FIT_OUT = Path("docs/api/champ-archetype-fit.json")
# Empirical ability axes (scaling = WR(long games) - WR(short); snowball =
# killing-spree / multi-kill blend), a participant-stats pass over the same pooled
# parquet.  Same lifecycle as the comp-fit radar: regenerated by
# scripts/build_champ_empirical_axes.py AFTER the tier list (its generator reads
# the rebuilt tier-list.json for champ names) and shipped in the same commit.  It
# drives the site's 後期 / 滾雪球 ability bars; if a deploy omits it the frontend
# fetch 404s and those two bars silently read 0 for every champion.
EMPIRICAL_AXES_OUT = Path("docs/api/champ-empirical-axes.json")
COMP_FIT_PARQUET_CANDIDATES = (
    Path("data/raw/mayhem_pooled_auto.parquet"),
    Path("data/raw/mayhem_pooled_16_10_12.parquet"),
)

DEFAULT_DOC_PATHS = (
    Path("docs/index.html"),
    Path("docs/api/tier-list.json"),
    # Per-champion detail shards are loaded on demand from the tier-list shell.
    # They must be staged atomically with the summary payload that references them.
    Path("docs/api/champions"),
    # Empirical comp-fit radar -- a decoupled artifact the frontend fetches on its
    # own.  A NEW required file: if a deploy omits it the live site's fetch 404s
    # and every champion silently falls back to the heuristic ("estimated") radar.
    COMP_FIT_OUT,
    # Empirical ability axes (scaling + snowball) -- a third decoupled fetch that
    # drives the 後期 / 滾雪球 ability bars.  Also required: if omitted the fetch
    # 404s and those two bars silently read 0 across every champion.
    EMPIRICAL_AXES_OUT,
    # Self-hosted CommunityDragon icons (Mayhem-only items + every augment).
    # build_tier_list.py downloads these under docs/assets/icons and rewrites the
    # payload to site-relative paths; they must be committed alongside the HTML /
    # JSON or the live site would 404 on every self-hosted icon.
    Path("docs/assets/icons"),
    # Hand-made article cover banners (專欄 首圖).  Referenced from the HTML as
    # assets/covers/<file>; must be committed alongside the HTML or the live site
    # 404s on any article that sets cover_image_*.
    Path("docs/assets/covers"),
    # The site's app script, emitted as an external cacheable asset (stable
    # filename, content-hash ?v= in the HTML).  A NEW required file: if a deploy
    # omits it the freshly published index.html loads a stale script (or 404s on
    # a first-ever deploy) and the SPA never boots.
    Path("docs/assets/site.js"),
    # Clean-path deep-link shells + locale mirrors, regenerated by render_html's
    # route_specs on every build (404.html, the main-tab stubs, and the /en and
    # /zh-CN homes + tab mirrors).  Each embeds the current game count, patch and
    # og-image cache-bust, so they change whenever index.html does.  They were
    # historically absent from this list, so every build regenerated them but the
    # publish never staged them: the live /en, /zh-CN and every shared deep link
    # kept an ever-older game count, and the social share thumbnail (og-image.png,
    # below) stayed frozen at whatever commit last hand-staged it.  Tracking them
    # here is what keeps the locale pages and share cards current.
    Path("docs/404.html"),
    Path("docs/augments"),
    Path("docs/changes"),
    Path("docs/draft"),
    Path("docs/game"),
    Path("docs/column"),
    Path("docs/en"),
    Path("docs/zh-CN"),
    # Social share thumbnail (og:image / twitter:image).  Re-rendered every build
    # with the live champion data + game count; referenced by every shell above
    # via a content-hash cache-bust.  Must ship with them or the share preview is stale.
    Path("docs/og-image.png"),
    # Static info pages (write_site_info_pages): about / privacy / contact.  Each
    # embeds a "last updated" date rewritten on every build, so like the shells
    # above they drift out of the publish and the live pages show an ever-older
    # date.  Same fix -- track them so they commit with the rest.
    Path("docs/about"),
    Path("docs/privacy"),
    Path("docs/contact"),
    # Build artifact (champion role spec) regenerated with the current patch each
    # build.  The live site does not fetch it -- only the offline
    # build_semantic_score_review_page.py reads it -- so its staleness is harmless
    # to users, but leaving it untracked means it shows as drift in every git
    # status and has to be hand-staged.  Committing it with each publish keeps the
    # tree clean and the offline consumer current.
    Path("docs/champion-roles.json"),
)


@dataclass(frozen=True)
class StaticPublishDecision:
    should_publish: bool
    local_total: int
    last_published_total: int
    threshold: int
    growth_ratio: float
    reason: str


@dataclass(frozen=True)
class CommandResult:
    returncode: int
    stdout: str = ""
    stderr: str = ""


CommandRunner = Callable[[Sequence[str]], CommandResult]


def load_state(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def save_state(path: Path, state: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")


def _state_int(value: Any) -> int:
    try:
        return max(0, int(value or 0))
    except (TypeError, ValueError):
        return 0


def _last_total_for_scope(
    state: dict[str, Any], *, patch_prefix: str | None, total_key: str
) -> tuple[int, str]:
    if patch_prefix:
        patches = state.get("patches")
        if isinstance(patches, dict):
            patch_state = patches.get(patch_prefix)
            if isinstance(patch_state, dict) and total_key in patch_state:
                return _state_int(patch_state.get(total_key)), "patch state"
        if state.get("last_patch_prefix") == patch_prefix:
            return _state_int(state.get(total_key)), "legacy state"
        return 0, "new patch baseline"
    return _state_int(state.get(total_key)), "global state"


def _effective_threshold(*, last_total: int, threshold: int, growth_ratio: float) -> int:
    absolute_threshold = max(0, int(threshold or 0))
    ratio_threshold = 0
    if growth_ratio > 0:
        ratio_threshold = max(1, math.ceil(max(0, last_total) * growth_ratio))
    return max(1, absolute_threshold, ratio_threshold)


def _decision_reason(
    *,
    delta: int,
    threshold: int,
    absolute_threshold: int,
    growth_ratio: float,
    baseline_source: str,
    patch_prefix: str | None,
    passed: bool,
) -> str:
    op = ">=" if passed else "<"
    reason = f"delta {delta} {op} {threshold}"
    if growth_ratio > 0 and threshold > max(0, int(absolute_threshold or 0)):
        reason += f" (growth {growth_ratio:.0%})"
    if baseline_source == "new patch baseline" and patch_prefix:
        reason += f"; first publish baseline for patch {patch_prefix}"
    return reason


def _record_patch_state(
    state: dict[str, Any], *, patch_prefix: str | None, payload: dict[str, Any]
) -> None:
    state.update(payload)
    if not patch_prefix:
        return
    patches = state.get("patches")
    if not isinstance(patches, dict):
        patches = {}
        state["patches"] = patches
    patch_state = patches.get(patch_prefix)
    if not isinstance(patch_state, dict):
        patch_state = {}
    patch_state.update(payload)
    patches[patch_prefix] = patch_state


def decide_static_publish(
    *,
    db: Path,
    state: dict[str, Any],
    threshold: int,
    force: bool,
    growth_ratio: float = 0.0,
    queue_id: int = 2400,
    patch_prefix: str | None = None,
) -> StaticPublishDecision:
    local_total = count_games(db, queue_id=queue_id, patch_prefix=patch_prefix)
    last_published_total, baseline_source = _last_total_for_scope(
        state,
        patch_prefix=patch_prefix,
        total_key="last_published_total",
    )
    effective_threshold = _effective_threshold(
        last_total=last_published_total,
        threshold=threshold,
        growth_ratio=growth_ratio,
    )
    if force:
        return StaticPublishDecision(
            True,
            local_total,
            last_published_total,
            effective_threshold,
            growth_ratio,
            "force",
        )
    if local_total <= 0:
        return StaticPublishDecision(
            False,
            local_total,
            last_published_total,
            effective_threshold,
            growth_ratio,
            "no local games",
        )
    delta = local_total - last_published_total
    if delta >= effective_threshold:
        return StaticPublishDecision(
            True,
            local_total,
            last_published_total,
            effective_threshold,
            growth_ratio,
            _decision_reason(
                delta=delta,
                threshold=effective_threshold,
                absolute_threshold=threshold,
                growth_ratio=growth_ratio,
                baseline_source=baseline_source,
                patch_prefix=patch_prefix,
                passed=True,
            ),
        )
    return StaticPublishDecision(
        False,
        local_total,
        last_published_total,
        effective_threshold,
        growth_ratio,
        _decision_reason(
            delta=delta,
            threshold=effective_threshold,
            absolute_threshold=threshold,
            growth_ratio=growth_ratio,
            baseline_source=baseline_source,
            patch_prefix=patch_prefix,
            passed=False,
        ),
    )


def _default_runner(command: Sequence[str]) -> CommandResult:
    # CREATE_NO_WINDOW (Windows-only; 0 elsewhere) stops every git invocation from
    # popping a conhost window when run under the windowless pythonw watchdog/publisher.
    completed = subprocess.run(
        command,
        text=True,
        capture_output=True,
        check=False,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )
    return CommandResult(completed.returncode, completed.stdout, completed.stderr)


def _run_checked(runner: CommandRunner, command: Sequence[str]) -> CommandResult:
    result = runner(command)
    if result.returncode != 0:
        rendered = " ".join(command)
        detail = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(f"command failed ({rendered}): {detail}")
    return result


def git_output(runner: CommandRunner, command: Sequence[str]) -> str:
    result = _run_checked(runner, command)
    return result.stdout.strip()


def merge_upstream(runner: CommandRunner, branch: str) -> str | None:
    """Merge any new origin/<branch> commits so the publish push fast-forwards.

    A commit pushed to the branch from anywhere else (another machine, the GitHub
    web UI) used to wedge this publisher permanently: every cycle rebuilt, staged
    and committed fine, then died on `push` with non-fast-forward -- the site sat
    17 hours stale behind a perfectly healthy crawler.

    Merge, not rebase: this repo's working tree is habitually dirty with WIP
    scripts, which rebase refuses outright while merge tolerates as long as the
    incoming commits leave those paths alone.  A real conflict is a human's call,
    so abort and let the error reach the alert instead of guessing a resolution.
    """
    # Plain `fetch origin`, not `fetch origin <branch>`: only the configured
    # refspec is guaranteed to update refs/remotes/origin/<branch>, which is what
    # the behind-count below reads.  The branch-specific form only promises
    # FETCH_HEAD.
    _run_checked(runner, ["git", "fetch", "origin"])
    behind = git_output(runner, ["git", "rev-list", "--count", f"HEAD..origin/{branch}"])
    if behind in {"", "0"}:
        return None
    result = runner(["git", "merge", "--no-edit", f"origin/{branch}"])
    if result.returncode != 0:
        runner(["git", "merge", "--abort"])
        detail = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(
            f"cannot merge {behind} upstream commit(s) from origin/{branch}: {detail}"
        )
    return f"merged {behind} upstream commit(s) from origin/{branch}"


def push_with_upstream_merge(runner: CommandRunner, branch: str) -> str | None:
    """Push, absorbing upstream commits first and once more if we lose a race."""
    merged = merge_upstream(runner, branch)
    result = runner(["git", "push", "origin", branch])
    if result.returncode == 0:
        return merged
    # Something landed upstream between our fetch and our push. Absorb it and
    # retry once; a second failure is not a race and should surface.
    merged = merge_upstream(runner, branch) or merged
    _run_checked(runner, ["git", "push", "origin", branch])
    return merged


def dirty_paths(runner: CommandRunner, paths: Sequence[Path]) -> list[str]:
    command = ["git", "status", "--short", "--", *(str(path) for path in paths)]
    output = git_output(runner, command)
    dirty: list[str] = []
    for line in output.splitlines():
        if not line.strip():
            continue
        # Untracked outputs ('??') are about to be regenerated and staged by the
        # publish itself (e.g. a brand-new docs/api/champ-archetype-fit.json or a
        # freshly downloaded icon), so they are not a reason to refuse.  Only
        # tracked modifications -- manual edits we would clobber -- should block.
        if line[:2] == "??":
            continue
        dirty.append(line)
    return dirty


def docs_have_diff(runner: CommandRunner, paths: Sequence[Path]) -> bool:
    command = ["git", "diff", "--quiet", "--", *(str(path) for path in paths)]
    result = runner(command)
    if result.returncode == 0:
        return False
    if result.returncode == 1:
        return True
    detail = result.stderr.strip() or result.stdout.strip()
    raise RuntimeError(f"git diff failed: {detail}")


def current_branch(runner: CommandRunner) -> str:
    return git_output(runner, ["git", "rev-parse", "--abbrev-ref", "HEAD"])


def build_split_site(
    *,
    runner: CommandRunner,
    site_url: str = DEFAULT_SITE_URL,
    queue_id: int = 2400,
    patch_prefix: str | None = None,
) -> None:
    command = [
        sys.executable,
        "scripts/build_tier_list.py",
        "--site-url",
        site_url,
        "--payload-out",
        "docs/api/tier-list.json",
        "--payload-url",
        "api/tier-list.json",
        "--queue",
        str(queue_id),
    ]
    if patch_prefix is not None:
        command.extend(["--patch-prefix", patch_prefix])
    if DEFAULT_CF_ANALYTICS_TOKEN:
        command.extend(["--cloudflare-analytics-token", DEFAULT_CF_ANALYTICS_TOKEN])
    _run_checked(runner, command)


def resolve_comp_fit_parquet(parquet: Path | None) -> Path | None:
    """Pick the pooled parquet the comp-fit build should read.

    An explicit *parquet* is trusted as-is (the build subprocess validates it).
    Otherwise prefer the auto-maintained pool the +25% recommender refresh keeps
    current, then the fixed 16.10-16.12 snapshot, else None (no data -> skip).
    """
    if parquet is not None:
        return parquet
    for candidate in COMP_FIT_PARQUET_CANDIDATES:
        if candidate.exists():
            return candidate
    return None


def build_champ_archetype_fit(
    *,
    runner: CommandRunner,
    parquet: Path | None = None,
    payload: Path = COMP_FIT_PAYLOAD,
    out: Path = COMP_FIT_OUT,
) -> dict[str, Any]:
    """Regenerate the empirical (champion x team-archetype) comp-fit radar.

    Must run AFTER build_split_site: it reads the freshly rebuilt tier-list.json
    champ.comp vectors.  Deliberately NON-FATAL -- a failure here (e.g. the pooled
    parquet is briefly mid-rewrite by the recommender refresh, or the data is
    missing) must not block the tier-list publish.  The frontend falls back to the
    heuristic radar when the artifact is stale/missing, so the worst case is a
    slightly old radar, logged loudly rather than a blocked deploy.
    """
    resolved = resolve_comp_fit_parquet(parquet)
    if resolved is None:
        candidates = ", ".join(str(c) for c in COMP_FIT_PARQUET_CANDIDATES)
        print(
            "[static-site] WARN: comp-fit pooled parquet not found "
            f"(looked for: {candidates}); skipping champ-archetype-fit refresh, "
            "the previous radar artifact ships unchanged.",
            file=sys.stderr,
        )
        return {"built": False, "reason": "parquet missing", "parquet": None}
    command = [
        sys.executable,
        "scripts/build_champ_archetype_fit.py",
        "--data",
        str(resolved),
        "--payload",
        str(payload),
        "--out",
        str(out),
    ]
    result = runner(command)
    if result.returncode != 0:
        detail = (result.stderr.strip() or result.stdout.strip())[:500]
        print(
            f"[static-site] WARN: comp-fit build failed (data={resolved}); "
            f"publishing the tier list with the previous radar artifact: {detail}",
            file=sys.stderr,
        )
        return {"built": False, "reason": "build failed", "parquet": str(resolved)}
    return {"built": True, "reason": "ok", "parquet": str(resolved)}


def build_champ_empirical_axes(
    *,
    runner: CommandRunner,
    parquet: Path | None = None,
    out: Path = EMPIRICAL_AXES_OUT,
) -> dict[str, Any]:
    """Regenerate the empirical ability axes (scaling + snowball) artifact.

    Like build_champ_archetype_fit, must run AFTER build_split_site: the generator
    reads the freshly rebuilt docs/api/tier-list.json (for champ names) plus the
    pooled parquet, and ships in the SAME commit as the tier list it depends on.
    Reuses the comp-fit parquet resolution (prefer the auto-maintained pool, fall
    back to the fixed 16.10-12 snapshot) so both empirical artifacts read the same
    window.  Deliberately NON-FATAL -- a failure here (parquet mid-rewrite, missing
    data, etc.) must never block the tier-list publish; the frontend just renders
    the previous (or zero) 後期 / 滾雪球 bars, logged loudly rather than blocking.
    """
    resolved = resolve_comp_fit_parquet(parquet)
    if resolved is None:
        candidates = ", ".join(str(c) for c in COMP_FIT_PARQUET_CANDIDATES)
        print(
            "[static-site] WARN: empirical-axes pooled parquet not found "
            f"(looked for: {candidates}); skipping champ-empirical-axes refresh, "
            "the previous scaling/snowball artifact ships unchanged.",
            file=sys.stderr,
        )
        return {"built": False, "reason": "parquet missing", "parquet": None}
    command = [
        sys.executable,
        "scripts/build_champ_empirical_axes.py",
        "--data",
        str(resolved),
        "--out",
        str(out),
    ]
    result = runner(command)
    if result.returncode != 0:
        detail = (result.stderr.strip() or result.stdout.strip())[:500]
        print(
            f"[static-site] WARN: empirical-axes build failed (data={resolved}); "
            f"publishing the tier list with the previous scaling/snowball artifact: {detail}",
            file=sys.stderr,
        )
        return {"built": False, "reason": "build failed", "parquet": str(resolved)}
    return {"built": True, "reason": "ok", "parquet": str(resolved)}


def publish_static_site_once(
    *,
    db: Path = Path("data/lcu/games.db"),
    state_path: Path = DEFAULT_STATE_PATH,
    threshold: int = 0,
    growth_ratio: float = 0.10,
    force: bool = False,
    queue_id: int = 2400,
    patch_prefix: str | None = None,
    site_url: str = DEFAULT_SITE_URL,
    branch: str = "main",
    check_only: bool = False,
    dry_run: bool = False,
    comp_fit_parquet: Path | None = None,
    runner: CommandRunner = _default_runner,
) -> dict[str, Any]:
    state = load_state(state_path)
    decision = decide_static_publish(
        db=db,
        state=state,
        threshold=threshold,
        growth_ratio=growth_ratio,
        force=force,
        queue_id=queue_id,
        patch_prefix=patch_prefix,
    )
    if not decision.should_publish:
        return {
            "published": False,
            "would_publish": False,
            "reason": decision.reason,
            "local_total": decision.local_total,
            "last_published_total": decision.last_published_total,
            "threshold": decision.threshold,
            "growth_ratio": decision.growth_ratio,
        }
    if check_only:
        return {
            "published": False,
            "would_publish": True,
            "reason": "check only: " + decision.reason,
            "local_total": decision.local_total,
            "last_published_total": decision.last_published_total,
            "threshold": decision.threshold,
            "growth_ratio": decision.growth_ratio,
        }

    branch_name = current_branch(runner)
    if branch_name != branch:
        raise RuntimeError(f"refusing to publish from branch {branch_name!r}; expected {branch!r}")

    preexisting = dirty_paths(runner, DEFAULT_DOC_PATHS)
    if preexisting:
        raise RuntimeError("refusing to overwrite dirty site output files: " + "; ".join(preexisting))

    build_split_site(runner=runner, site_url=site_url, queue_id=queue_id, patch_prefix=patch_prefix)
    # Regenerate the empirical comp-fit radar from the just-rebuilt tier-list.json
    # so it ships in the SAME commit as the tier list it depends on.  Non-fatal:
    # a comp-fit failure must never block the tier-list publish.
    comp_fit = build_champ_archetype_fit(runner=runner, parquet=comp_fit_parquet)
    # Regenerate the empirical ability axes (scaling + snowball) from the same
    # rebuilt tier-list.json + pooled parquet so the 後期 / 滾雪球 bars ship in the
    # same commit.  Also non-fatal -- a failure here must never block the publish.
    empirical_axes = build_champ_empirical_axes(runner=runner, parquet=comp_fit_parquet)

    changed = docs_have_diff(runner, DEFAULT_DOC_PATHS)
    if not changed:
        _record_patch_state(
            state,
            patch_prefix=patch_prefix,
            payload={
                "last_published_total": decision.local_total,
                "last_publish_at_unix": time.time(),
                "last_result": "no docs diff after rebuild",
                "last_queue_id": queue_id,
                "last_patch_prefix": patch_prefix,
                "last_threshold": decision.threshold,
                "last_growth_ratio": decision.growth_ratio,
            },
        )
        if not dry_run:
            save_state(state_path, state)
        return {
            "published": False,
            "would_publish": False,
            "reason": "no docs diff after rebuild",
            "local_total": decision.local_total,
            "last_published_total": decision.last_published_total,
            "threshold": decision.threshold,
            "growth_ratio": decision.growth_ratio,
            "comp_fit": comp_fit,
            "empirical_axes": empirical_axes,
        }

    today = dt.date.today().isoformat()
    message = f"Refresh split tier list {today}"

    if dry_run:
        return {
            "published": False,
            "would_publish": True,
            "reason": "dry run",
            "local_total": decision.local_total,
            "last_published_total": decision.last_published_total,
            "threshold": decision.threshold,
            "growth_ratio": decision.growth_ratio,
            "changed_paths": [path.as_posix() for path in DEFAULT_DOC_PATHS],
            "commit_message": message,
            "comp_fit": comp_fit,
            "empirical_axes": empirical_axes,
        }

    _run_checked(runner, ["git", "add", *(str(path) for path in DEFAULT_DOC_PATHS)])
    _run_checked(runner, ["git", "commit", "-m", message])
    merged = push_with_upstream_merge(runner, branch)
    commit = git_output(runner, ["git", "rev-parse", "--short", "HEAD"])

    _record_patch_state(
        state,
        patch_prefix=patch_prefix,
        payload={
            "last_published_total": decision.local_total,
            "last_publish_at_unix": time.time(),
            "last_commit": commit,
            "last_queue_id": queue_id,
            "last_patch_prefix": patch_prefix,
            "last_result": "published",
            "last_threshold": decision.threshold,
            "last_growth_ratio": decision.growth_ratio,
        },
    )
    save_state(state_path, state)

    return {
        "published": True,
        "would_publish": True,
        "reason": decision.reason,
        "local_total": decision.local_total,
        "last_published_total": decision.last_published_total,
        "threshold": decision.threshold,
        "growth_ratio": decision.growth_ratio,
        "commit": commit,
        "merged_upstream": merged,
        "changed_paths": [path.as_posix() for path in DEFAULT_DOC_PATHS],
        "commit_message": message,
        "comp_fit": comp_fit,
        "empirical_axes": empirical_axes,
    }
